import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.84.0";

/**
 * Canonical Shepherd Neame Organization description (ORG_DESCRIPTION)
 * 
 * IMPORTANT: This must stay in sync with src/config/organization.ts
 * This is the single source of truth for the Organization node description.
 */
const ORG_DESCRIPTION =
  "Shepherd Neame Limited is listed on the Aquis Stock Exchange and is Britain's oldest brewer, based in Faversham, Kent. It owns and operates a large estate of pubs and hotels across Kent, London and the South East.";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface GenerateSchemaRequest {
  page_id: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log("generate-schema function called");

    // Create Supabase client
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Check if this is a service role call (internal/automated)
    const authHeader = req.headers.get("Authorization");
    const isServiceRoleCall = authHeader?.includes(supabaseServiceKey);

    let userId: string | null = null;

    if (!isServiceRoleCall) {
      // Regular user call - require authentication
      if (!authHeader) {
        return new Response(
          JSON.stringify({ error: "Unauthorized" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const { data: { user }, error: authError } = await supabase.auth.getUser(
        authHeader.replace("Bearer ", "")
      );
      if (authError || !user) {
        return new Response(
          JSON.stringify({ error: "Unauthorized" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      userId = user.id;
    } else {
      console.log("Service role call detected - proceeding without user auth");
      // userId remains null for automated calls
    }

    // Parse request body
    const { page_id }: GenerateSchemaRequest = await req.json();

    if (!page_id) {
      return new Response(
        JSON.stringify({ error: "page_id is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log("Generating schema for page:", page_id);

    // 1. Load page context (including wikidata_qid for sameAs injection)
    const { data: page, error: pageError } = await supabase
      .from("pages")
      .select("id, path, section, page_type, category, faq_mode, logo_url, hero_image_url, is_home_page, domain, beer_abv, beer_style, beer_launch_year, beer_official_url, last_html_hash, has_faq, notes, wikidata_qid")
      .eq("id", page_id)
      .single();

    if (pageError || !page) {
      console.error("Error fetching page:", pageError);
      return new Response(
        JSON.stringify({ error: "Page not found" }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ========================================
    // HOMEPAGE PROTECTION
    // ----------------------------------------
    // Homepage schema is managed manually by admins only.
    // AI generation is explicitly disabled for the homepage.
    // ========================================
    if (page.is_home_page) {
      console.log("Homepage detected - AI generation blocked (manual-only)");
      return new Response(
        JSON.stringify({ error: "Homepage schema is managed manually and cannot be generated by AI." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ========================================
    // DOMAIN LANE LOGIC
    // ----------------------------------------
    // 'Corporate' & 'Beer' - Use the rules-based schema engine with page_type + category matching
    // 'Pub' - Individual pub/hotel pages (Phase 2 - UI blocks this)
    // ========================================

    // Defensive check: UI should prevent Pub calls, but handle gracefully if reached
    const pageDomain = page.domain || 'Corporate'; // Default to Corporate for existing records
    
    if (pageDomain === 'Pub') {
      console.log("Pub lane - should not reach edge function (UI should block)");
      return new Response(
        JSON.stringify({ error: "Pub schema generation is not yet implemented (Phase 2)" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ========================================
    // RULES-BASED SCHEMA ENGINE (Corporate & Beer)
    // Uses page_type + category to select the correct active rule
    // All logic below this point uses the rules system
    // ========================================

    // Check if HTML has been fetched
    if (!page.last_html_hash) {
      return new Response(
        JSON.stringify({ error: "HTML not fetched yet. Please fetch HTML first." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Load settings for canonical_base_url
    const { data: settings, error: settingsError } = await supabase
      .from("settings")
      .select("*")
      .single();

    if (settingsError || !settings) {
      console.error("Error fetching settings:", settingsError);
      return new Response(
        JSON.stringify({ error: "Settings not found" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Check schema engine version first to determine which rules to load
    const schemaEngineVersion = settings.schema_engine_version || "v1";
    
    // For v1, load the active rule from rules table
    let activeRule = null;
    if (schemaEngineVersion === "v1") {
      const { data: rule, error: ruleError } = await supabase
        .from("rules")
        .select("*")
        .eq("is_active", true)
        .single();

      if (ruleError || !rule) {
        console.error("Error fetching active rule:", ruleError);
        return new Response(
          JSON.stringify({ error: "No active rule found. Please activate a rule first." }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      activeRule = rule;
    }

    // Fetch the HTML again (we could store it but for now we refetch)
    const fetchUrl = `${settings.fetch_base_url}${page.path}`;
    const fetchHeaders: HeadersInit = {
      "User-Agent": "NeameGraph-SchemaGenerator/1.0",
    };

    if (settings.preview_auth_user && settings.preview_auth_password) {
      const credentials = btoa(`${settings.preview_auth_user}:${settings.preview_auth_password}`);
      fetchHeaders["Authorization"] = `Basic ${credentials}`;
    }

    const htmlResponse = await fetch(fetchUrl, {
      headers: fetchHeaders,
      redirect: "follow",
    });

    if (!htmlResponse.ok) {
      console.error("Failed to fetch HTML:", htmlResponse.status);
      return new Response(
        JSON.stringify({ error: "Failed to fetch HTML for schema generation" }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const html = await htmlResponse.text();
    console.log("HTML fetched for schema generation, length:", html.length);

    // Trim HTML to reasonable size (keep first 50k characters to avoid token limits)
    const trimmedHtml = html.length > 50000 ? html.substring(0, 50000) + "\n<!-- HTML truncated for AI processing -->" : html;

    // Build canonical_url
    const canonicalBaseUrl = settings.canonical_base_url.replace(/\/$/, "");
    const canonicalUrl = `${canonicalBaseUrl}${page.path}`;
    
    if (schemaEngineVersion === "v2") {
      // Validate v2 requirements
      const v2PageTypes = [
        "Pubs & Hotels Estate",
        "Beers",
        "Brewery",
        "History",
        "Environment",
        "About",
        "Careers",
        "News"
      ];
      
      if (!page.page_type || !v2PageTypes.includes(page.page_type)) {
        return new Response(
          JSON.stringify({ 
            error: "Corporate v2 schema generation requires a valid Page Type. Please set the Page Type before generating schema.",
            validation_errors: ["Missing or invalid page_type for v2"]
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Load v2 rules from the rules table based on page_type AND category
      console.log(`Loading v2 rules for pageType: ${page.page_type}, category: ${page.category || 'none'}`);
      
      // 1) Try to find a specific rule for this page type + category (is_active = true)
      let { data: matchedRule, error: matchError } = await supabase
        .from("rules")
        .select("*")
        .eq("page_type", page.page_type)
        .eq("category", page.category)
        .eq("is_active", true)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle();

      // 2) If no specific rule found, fall back to the default rule (page_type AND category both NULL)
      if (!matchedRule) {
        const { data: defaultRule } = await supabase
          .from("rules")
          .select("*")
          .is("page_type", null)
          .is("category", null)
          .eq("is_active", true)
          .order("created_at", { ascending: false })
          .limit(1)
          .maybeSingle();
        
        matchedRule = defaultRule;
        
        if (matchedRule) {
          console.log(`Using default rule (page_type=null, category=null): ${matchedRule.name}`);
        }
      } else {
        console.log(`Using specific rule for ${page.page_type} · ${page.category}: ${matchedRule.name}`);
      }

      if (!matchedRule) {
        return new Response(
          JSON.stringify({ 
            error: `No active rule found for page type "${page.page_type}" and category "${page.category || 'none'}". Please create a rule for this combination or set a default rule.`
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const v2Rules = matchedRule.body;
      const usedRuleId = matchedRule.id;
      console.log(`Using rule: ${matchedRule.name} (${matchedRule.page_type || 'any'} · ${matchedRule.category || 'baseline'})`);
      console.log(`v2 rules loaded, length: ${v2Rules.length}`);

      // Build v2 user message with rules at the top
      const v2UserMessage = `
${v2Rules}

---

Generate JSON-LD schema for the following page:

Canonical URL: ${canonicalUrl}
Path: ${page.path}
Page Type: ${page.page_type}
Category: ${page.category || "N/A"}
FAQ Mode: ${page.faq_mode || "auto"}
Logo URL: ${page.logo_url || "none"}
Hero Image URL: ${page.hero_image_url || "none"}

HTML Content:
${trimmedHtml}

CRITICAL: Return ONLY valid JSON-LD. Start with { and end with }. Do not include markdown code blocks, explanations, or any other text. The response must be parseable by JSON.parse().
`;

      console.log("Calling Lovable AI for v2 schema generation...");

      // Call Lovable AI with v2 rules
      const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
      if (!LOVABLE_API_KEY) {
        return new Response(
          JSON.stringify({ error: "LOVABLE_API_KEY not configured" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const v2AiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${LOVABLE_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-2.5-flash",
          messages: [
            { role: "system", content: "You are a corporate schema.org JSON-LD generator. Follow all rules provided." },
            { role: "user", content: v2UserMessage }
          ],
        }),
      });

      if (!v2AiResponse.ok) {
        const errorText = await v2AiResponse.text();
        console.error("AI API error (v2):", v2AiResponse.status, errorText);
        
        if (v2AiResponse.status === 429) {
          return new Response(
            JSON.stringify({ error: "Rate limit exceeded. Please try again later." }),
            { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }
        
        if (v2AiResponse.status === 402) {
          return new Response(
            JSON.stringify({ error: "Payment required. Please add credits to your Lovable AI workspace." }),
            { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }

        return new Response(
          JSON.stringify({ error: "AI API error" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const v2AiData = await v2AiResponse.json();
      const v2GeneratedContent = v2AiData.choices?.[0]?.message?.content;

      if (!v2GeneratedContent) {
        console.error("No content in v2 AI response");
        return new Response(
          JSON.stringify({ error: "AI returned no content" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      console.log("v2 AI response received, length:", v2GeneratedContent.length);

      // Parse and validate v2 response
      let v2Jsonld;
      try {
        let jsonContent = v2GeneratedContent.trim();
        
        // Remove markdown code blocks if present
        if (jsonContent.startsWith("```")) {
          const match = jsonContent.match(/```(?:json|jsonld)?\s*([\s\S]*?)```/);
          if (match) {
            jsonContent = match[1].trim();
          }
        }
        
        // Remove any leading/trailing text that's not JSON
        const jsonStart = jsonContent.indexOf('{');
        const jsonEnd = jsonContent.lastIndexOf('}');
        
        if (jsonStart !== -1 && jsonEnd !== -1 && jsonEnd > jsonStart) {
          jsonContent = jsonContent.substring(jsonStart, jsonEnd + 1);
        }
        
        // Try to parse
        v2Jsonld = JSON.parse(jsonContent);
      } catch (parseError) {
        console.error("Failed to parse v2 AI response as JSON:", parseError);
        console.error("AI response (first 1000 chars):", v2GeneratedContent.substring(0, 1000));
        return new Response(
          JSON.stringify({
            error: "AI did not return valid JSON. The schema generation prompt may need refinement, or the AI may be having difficulty with this page content.",
            details: v2GeneratedContent.substring(0, 500),
            parseError: parseError instanceof Error ? parseError.message : String(parseError)
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Basic v2 validation
      const v2ValidationErrors: string[] = [];

      if (!v2Jsonld["@context"]) {
        v2ValidationErrors.push("Missing @context");
      }

      if (!v2Jsonld["@graph"] || !Array.isArray(v2Jsonld["@graph"])) {
        v2ValidationErrors.push("Missing or invalid @graph array");
      }

      if (v2ValidationErrors.length > 0) {
        console.error("v2 Validation errors:", v2ValidationErrors);
        return new Response(
          JSON.stringify({
            error: "Schema validation failed",
            validation_errors: v2ValidationErrors
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // ========================================
      // SCHEMA QUALITY CHARTER ENFORCEMENT
      // ----------------------------------------
      // Post-process the AI-generated JSON-LD to enforce Charter rules:
      // 1. Always emit a proper WebSite node
      // 2. Make all WebPage nodes point to WebSite via isPartOf (not Organization)
      // 3. Ensure publisher correctly links back to canonical Organization
      // 4. Only emit FAQ schema when there is real on-page FAQ content
      // See docs/schema-quality-charter.md for quality standards
      // ========================================
      const graph = v2Jsonld["@graph"] || [];
      let charterWarnings: string[] = [];
      
      // STEP 1: Ensure canonical WebSite node exists
      // Required by Charter: single WebSite node that all WebPage nodes link to
      const websiteId = "https://www.shepherdneame.co.uk/#website";
      const orgId = "https://www.shepherdneame.co.uk/#organization";
      
      let websiteNode = graph.find((node: any) => node["@id"] === websiteId);
      
      if (!websiteNode) {
        // Create the canonical WebSite node
        websiteNode = {
          "@type": "WebSite",
          "@id": websiteId,
          "url": "https://www.shepherdneame.co.uk",
          "name": "Shepherd Neame",
          "publisher": { "@id": orgId }
        };
        graph.push(websiteNode);
        console.log("✓ Added canonical WebSite node");
      } else {
        // Ensure existing WebSite has correct publisher
        websiteNode.publisher = { "@id": orgId };
        console.log("✓ Updated existing WebSite node");
      }
      
      // STEP 1a: Ensure canonical Organization node has correct description
      // Charter requirement: Organization description must use ORG_DESCRIPTION
      let orgNode = graph.find((node: any) => node["@id"] === orgId);
      
      if (orgNode) {
        // Update existing Organization node with canonical description
        orgNode.description = ORG_DESCRIPTION;
        console.log("✓ Updated Organization node description");
      } else {
        // Create minimal Organization node if missing (should be generated by AI)
        orgNode = {
          "@type": ["Organization", "Corporation"],
          "@id": orgId,
          "name": "Shepherd Neame Limited",
          "url": "https://www.shepherdneame.co.uk",
          "description": ORG_DESCRIPTION
        };
        graph.push(orgNode);
        console.log("✓ Added canonical Organization node");
      }
      
      // STEP 2: Fix isPartOf on all WebPage nodes
      // Charter rule: WebPage nodes must link to WebSite via isPartOf, not Organization
      // NOTE: This filter only matches primary WebPage nodes, not specialized types like FAQPage
      // to avoid false positives in Charter validation (e.g. WebPage + FAQPage is a valid pattern)
      let webPageNodes = graph.filter((node: any) => {
        const types = Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]];
        return types.includes("WebPage");
      });
      
      webPageNodes.forEach((node: any) => {
        // Set isPartOf to WebSite (not Organization)
        node.isPartOf = { "@id": websiteId };
      });
      
      if (webPageNodes.length > 0) {
        console.log(`✓ Fixed isPartOf for ${webPageNodes.length} WebPage node(s)`);
      }
      
      // STEP 3: Ensure WebPage nodes have publisher linking to Organization
      // Charter rule: key entities must explicitly link back to canonical Organization
      webPageNodes.forEach((node: any) => {
        if (!node.publisher) {
          node.publisher = { "@id": orgId };
        } else if (typeof node.publisher === "string") {
          // Normalize string to object form
          node.publisher = { "@id": orgId };
        }
      });
      
      console.log(`✓ Ensured publisher on ${webPageNodes.length} WebPage node(s)`);
      
      // STEP 4: Remove FAQ schema if not appropriate
      // Charter rule: FAQ schema only when real on-page FAQ content exists
      const shouldHaveFAQ = page.has_faq === true && page.faq_mode !== "ignore";
      
      if (!shouldHaveFAQ) {
        // Remove any FAQPage, Question, or Answer nodes
        const beforeLength = graph.length;
        for (let i = graph.length - 1; i >= 0; i--) {
          const node = graph[i];
          const types = Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]];
          
          if (types.includes("FAQPage") || types.includes("Question") || types.includes("Answer")) {
            graph.splice(i, 1);
          } else if (Array.isArray(node["@type"]) && node["@type"].includes("FAQPage")) {
            // Remove FAQPage from type array if present with other types
            node["@type"] = node["@type"].filter((t: string) => t !== "FAQPage");
            if (node["@type"].length === 0) {
              graph.splice(i, 1);
            }
          }
        }
        
        const removedCount = beforeLength - graph.length;
        if (removedCount > 0) {
          console.log(`✓ Removed ${removedCount} FAQ-related node(s) (no real FAQ content)`);
        }
      }
      
      // STEP 5: Clean up dangling hasPart references
      // Prevent validation errors like "hasPart references non-existent node .../Beers#brewery-faq"
      // This can happen when FAQ nodes are removed but hasPart still references them
      const existingIds = new Set(
        graph
          .map((node: any) => node["@id"])
          .filter((id: any) => typeof id === "string")
      );
      
      const cleanHasPart = (value: any) => {
        if (!value) return undefined;
        
        const toIds = (v: any): string[] => {
          if (!v) return [];
          if (typeof v === "string") return [v];
          if (Array.isArray(v)) return v.flatMap(toIds);
          if (typeof v === "object" && v["@id"]) return [v["@id"]];
          return [];
        };
        
        const ids = toIds(value).filter((id) => existingIds.has(id));
        
        if (ids.length === 0) return undefined;
        
        if (Array.isArray(value)) {
          // Return array of objects with @id
          return ids.map((id) => ({ "@id": id }));
        }
        
        // Single reference: return as object with @id
        return { "@id": ids[0] };
      };
      
      let cleanedHasPartCount = 0;
      graph.forEach((node: any) => {
        if (node.hasPart) {
          const cleaned = cleanHasPart(node.hasPart);
          if (cleaned) {
            node.hasPart = cleaned;
          } else {
            delete node.hasPart;
            cleanedHasPartCount++;
          }
        }
      });
      
      if (cleanedHasPartCount > 0) {
        console.log(`✓ Cleaned ${cleanedHasPartCount} dangling hasPart reference(s)`);
      }
      
      // STEP 6: Transform beer detail pages to use Product as main entity
      // Charter rule: Individual beer pages should model the beer as a Product
      // Collection pages (like /Beers) remain as ItemList/CollectionPage
      const isBeerDetailPage = page.page_type === "Beers" && page.category === "Drink Brands";
      
      if (isBeerDetailPage) {
        console.log("Beer detail page detected - transforming to Product schema");
        
        // Find the main WebPage node for this page
        const pageWebPageNode = graph.find((node: any) => {
          const types = Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]];
          return types.includes("WebPage") && node.url === canonicalUrl;
        });
        
        if (pageWebPageNode) {
          // Create Product node for the beer
          const productId = `${canonicalUrl}#product`;
          
          // Check if Product node already exists (AI might have created it)
          let productNode = graph.find((node: any) => node["@id"] === productId);
          
          if (!productNode) {
            // Extract beer name from WebPage node or page metadata
            const beerName = pageWebPageNode.name || page.path.split('/').pop()?.replace(/-/g, ' ');
            
            // Find hero image from page metadata or existing graph nodes
            let beerImage = page.hero_image_url || page.logo_url;
            
            // Try to find image from existing Brand or ImageObject nodes
            if (!beerImage) {
              const imageNode = graph.find((node: any) => {
                const types = Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]];
                return types.includes("ImageObject") && node.url;
              });
              if (imageNode) {
                beerImage = imageNode.url;
              }
            }
            
            // Create Product node
            productNode = {
              "@type": "Product",
              "@id": productId,
              "name": beerName,
              "url": canonicalUrl,
              "brand": { "@id": orgId },
              "manufacturer": { "@id": orgId }
            };
            
            // Add description from WebPage if available
            if (pageWebPageNode.description) {
              productNode.description = pageWebPageNode.description;
            }
            
            // Add image if available
            if (beerImage) {
              productNode.image = {
                "@type": "ImageObject",
                "url": beerImage
              };
            }
            
            // Add beer-specific metadata if available
            if (page.beer_abv) {
              productNode.alcoholByVolume = page.beer_abv.toString();
            }
            
            // Add additionalProperty for style if available
            if (page.beer_style) {
              productNode.additionalProperty = productNode.additionalProperty || [];
              productNode.additionalProperty.push({
                "@type": "PropertyValue",
                "name": "Style",
                "value": page.beer_style
              });
            }
            
            // Add launch year via releaseDate if available
            if (page.beer_launch_year) {
              productNode.releaseDate = page.beer_launch_year.toString();
            }
            
            // Add sameAs for wikidata if available
            if (page.wikidata_qid) {
              productNode.sameAs = [`https://www.wikidata.org/wiki/${page.wikidata_qid}`];
            }
            
            graph.push(productNode);
            console.log("✓ Created Product node for beer");
          } else {
            // Product node exists - ensure it has correct brand/manufacturer
            productNode.brand = { "@id": orgId };
            productNode.manufacturer = { "@id": orgId };
            console.log("✓ Updated existing Product node");
          }
          
          // Update WebPage's mainEntity to reference Product
          pageWebPageNode.mainEntity = { "@id": productId };
          pageWebPageNode.about = { "@id": productId };
          
          console.log("✓ Linked WebPage mainEntity to Product");
          
          // Remove any Brand nodes that were the main entity (beer should be Product, not Brand)
          // Keep Organization and other structural nodes
          const brandNodesToRemove: number[] = [];
          graph.forEach((node: any, index: number) => {
            const types = Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]];
            if (types.includes("Brand") && !types.includes("Organization") && node["@id"] !== orgId) {
              // Check if this Brand was the main entity
              const isMainEntity = node["@id"] && (
                pageWebPageNode.mainEntity?.["@id"] === node["@id"] ||
                pageWebPageNode.about?.["@id"] === node["@id"]
              );
              if (isMainEntity) {
                brandNodesToRemove.push(index);
              }
            }
          });
          
          // Remove Brand nodes in reverse order to maintain indices
          for (let i = brandNodesToRemove.length - 1; i >= 0; i--) {
            graph.splice(brandNodesToRemove[i], 1);
          }
          
          if (brandNodesToRemove.length > 0) {
            console.log(`✓ Removed ${brandNodesToRemove.length} Brand node(s) (replaced with Product)`);
          }
        }
      }
      
      // Update the graph in the jsonld object
      v2Jsonld["@graph"] = graph;
      
      // ========================================
      // SCHEMA QUALITY CHARTER VALIDATION
      // ----------------------------------------
      // Validate that enforcements worked correctly
      // ========================================

      // Rule: mustLinkToCanonicalOrg
      // Check for canonical Organization node
      const hasOrgNode = graph.some((node: any) =>
        node["@id"] === "https://www.shepherdneame.co.uk/#organization"
      );
      if (!hasOrgNode) {
        charterWarnings.push("CHARTER VIOLATION: Missing canonical Organization node (@id: https://www.shepherdneame.co.uk/#organization)");
      } else {
        // Check that key entities link to Organization (string or object form)
        const hasOrgReferences = graph.some((node: any) =>
          node.publisher === "https://www.shepherdneame.co.uk/#organization" ||
          (typeof node.publisher === "object" && node.publisher?.["@id"] === "https://www.shepherdneame.co.uk/#organization") ||
          node.manufacturer === "https://www.shepherdneame.co.uk/#organization" ||
          (typeof node.manufacturer === "object" && node.manufacturer?.["@id"] === "https://www.shepherdneame.co.uk/#organization") ||
          node.parentOrganization === "https://www.shepherdneame.co.uk/#organization" ||
          (typeof node.parentOrganization === "object" && node.parentOrganization?.["@id"] === "https://www.shepherdneame.co.uk/#organization") ||
          node.brand === "https://www.shepherdneame.co.uk/#organization" ||
          (typeof node.brand === "object" && node.brand?.["@id"] === "https://www.shepherdneame.co.uk/#organization")
        );
        if (!hasOrgReferences) {
          charterWarnings.push("CHARTER WARNING: No entities link to the canonical Organization node");
        }
      }

      // Rule: mustLinkToWebsite
      // Check that WebPage nodes link to WebSite via isPartOf (should be enforced already)
      const hasWebsiteLink = webPageNodes.every((node: any) =>
        node.isPartOf === "https://www.shepherdneame.co.uk/#website" ||
        (typeof node.isPartOf === "object" && node.isPartOf?.["@id"] === "https://www.shepherdneame.co.uk/#website")
      );
      if (webPageNodes.length > 0 && !hasWebsiteLink) {
        charterWarnings.push("CHARTER WARNING: Not all WebPage nodes link to the main Website via isPartOf");
      }

      // Rule: requireVisibleFAQForFAQSchema
      // Check if FAQ schema is present when faq_mode is not 'auto' or has_faq is false
      const hasFAQSchema = graph.some((node: any) => {
        const types = Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]];
        return types.includes("FAQPage") || types.includes("Question");
      });
      if (hasFAQSchema && (page.faq_mode === "ignore" || !page.has_faq)) {
        charterWarnings.push("CHARTER WARNING: FAQ schema present but FAQ mode is disabled or no FAQ content detected");
      }

      // Rule: enforceStableIds
      // Check for duplicate @id values
      const seenIds = new Set<string>();
      const duplicateIds: string[] = [];
      graph.forEach((node: any) => {
        if (node["@id"]) {
          if (seenIds.has(node["@id"])) {
            duplicateIds.push(node["@id"]);
          } else {
            seenIds.add(node["@id"]);
          }
        }
      });
      if (duplicateIds.length > 0) {
        charterWarnings.push(`CHARTER VIOLATION: Duplicate @id values found: ${duplicateIds.join(", ")}`);
      }

      // Rule: oneMainEntityPerPage
      // Count primary WebPage nodes with mainEntity or about properties
      // NOTE: This only checks true WebPage nodes, not specialized types like FAQPage
      // A WebPage + FAQPage combination is valid and should not trigger this warning
      const webPagesWithMainEntity = webPageNodes.filter((node: any) =>
        node.mainEntity || node.about
      );
      if (webPagesWithMainEntity.length > 1) {
        charterWarnings.push("CHARTER WARNING: Multiple WebPage nodes with mainEntity/about detected - page may have competing primary entities");
      }

      // Log all Charter warnings
      if (charterWarnings.length > 0) {
        console.warn("=== Schema Quality Charter Warnings ===");
        charterWarnings.forEach((warning) => console.warn(warning));
        console.warn("=======================================");
        console.warn(`Charter compliance: ${charterWarnings.filter(w => w.includes("VIOLATION")).length} violations, ${charterWarnings.filter(w => w.includes("WARNING")).length} warnings`);
        console.warn("See docs/schema-quality-charter.md for quality standards");
      } else {
        console.log("✓ Schema Quality Charter: All checks passed");
      }

      // ========================================
      // WIKIDATA SAMEAS INJECTION
      // ----------------------------------------
      // If this is a Beer page with a wikidata_qid, inject the sameAs URL
      // into the main Beer entity (typically a Brand node)
      // ========================================
      if (pageDomain === 'Beer' && page.wikidata_qid && v2Jsonld["@graph"]) {
        const wikidataUrl = `https://www.wikidata.org/wiki/${page.wikidata_qid}`;
        console.log(`Injecting Wikidata sameAs: ${wikidataUrl}`);
        
        // Find the main beer entity in the graph (typically has @type containing "Brand")
        // and inject/append sameAs
        const graph = v2Jsonld["@graph"];
        for (let i = 0; i < graph.length; i++) {
          const node = graph[i];
          const nodeTypes = Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]];
          
          // Look for Brand nodes (main beer entity)
          if (nodeTypes.includes("Brand")) {
            if (!node.sameAs) {
              node.sameAs = [wikidataUrl];
            } else if (Array.isArray(node.sameAs)) {
              if (!node.sameAs.includes(wikidataUrl)) {
                node.sameAs.push(wikidataUrl);
              }
            } else {
              // sameAs is a single string, convert to array
              node.sameAs = [node.sameAs, wikidataUrl];
            }
            console.log(`Added Wikidata sameAs to Brand node: ${node["@id"]}`);
            break; // Only inject once
          }
        }
      }

      // Save v2 schema version
      const v2JsonldString = JSON.stringify(v2Jsonld, null, 2);

      const encoder = new TextEncoder();
      const data = encoder.encode(v2JsonldString);
      const hashBuffer = await crypto.subtle.digest("SHA-256", data);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      const v2SchemaHash = hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");

      const { data: existingVersions, error: versionsError } = await supabase
        .from("schema_versions")
        .select("version_number")
        .eq("page_id", page_id)
        .order("version_number", { ascending: false })
        .limit(1);

      const nextVersionNumber = existingVersions && existingVersions.length > 0
        ? existingVersions[0].version_number + 1
        : 1;

      const { data: v2SchemaVersion, error: v2SchemaError } = await supabase
        .from("schema_versions")
        .insert({
          page_id: page_id,
          version_number: nextVersionNumber,
          jsonld: v2JsonldString,
          status: "draft",
          created_by_user_id: userId,
          rules_id: usedRuleId,
          google_rr_passed: false,
        })
        .select()
        .single();

      if (v2SchemaError) {
        console.error("Error saving v2 schema version:", v2SchemaError);
        return new Response(
          JSON.stringify({ error: "Failed to save schema version" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      await supabase
        .from("pages")
        .update({
          last_schema_generated_at: new Date().toISOString(),
          last_schema_hash: v2SchemaHash,
          status: "ai_draft",
          last_modified_by_user_id: userId,
        })
        .eq("id", page_id);

      await supabase.from("audit_log").insert({
        user_id: userId || "system",
        entity_type: "schema_version",
        entity_id: v2SchemaVersion.id,
        action: "generate_schema",
        details: {
          page_id: page_id,
          page_path: page.path,
          version_number: nextVersionNumber,
          engine_version: "v2",
          page_type: page.page_type,
          category: page.category,
        },
      });

      console.log("v2 Schema generation completed successfully");

      // charterWarnings is derived from the Schema Quality Charter checks and is used by the UI
      // to show Charter compliance per schema run. Empty array if no warnings.
      return new Response(
        JSON.stringify({
          success: true,
          schema_version: v2SchemaVersion,
          version_number: nextVersionNumber,
          engine_version: "v2",
          used_rule: {
            id: matchedRule.id,
            name: matchedRule.name,
            page_type: matchedRule.page_type,
            category: matchedRule.category,
          },
          charterWarnings, // String array of Charter compliance warnings
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Continue with v1 logic below...
    // 2. Call Lovable AI
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      return new Response(
        JSON.stringify({ error: "LOVABLE_API_KEY not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const userMessage = `
Generate JSON-LD schema for the following page:

Canonical URL: ${canonicalUrl}
Path: ${page.path}
Section: ${page.section || "unknown"}
Page Type: ${page.page_type || "unknown"}
Has FAQ: ${page.has_faq}
Notes: ${page.notes || "none"}

HTML Content:
${trimmedHtml}

CRITICAL REQUIREMENTS - Your response MUST include:
1. An "@context" field set to "https://schema.org"
2. An "@graph" array containing all entities
3. An Organization node with EXACTLY these properties:
   - "@type": ["Organization", "Corporation"]
   - "@id": "https://www.shepherdneame.co.uk/#organization"
   - "name": "Shepherd Neame Limited"
   - "url": "https://www.shepherdneame.co.uk"

   NOTE: In future versions, the Organization node should be sourced from settings.organization_schema_json 
   instead of being generated inline by the AI. This will ensure a single master Organization node across all pages.

Return ONLY the JSON-LD object. No explanations, no markdown code blocks, just the raw JSON starting with { and ending with }.
`;

    console.log("Calling Lovable AI...");

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: activeRule.body },
          { role: "user", content: userMessage }
        ],
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error("AI API error:", aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded. Please try again later." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      
      if (aiResponse.status === 402) {
        return new Response(
          JSON.stringify({ error: "Payment required. Please add credits to your Lovable AI workspace." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      return new Response(
        JSON.stringify({ error: "AI API error" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const aiData = await aiResponse.json();
    const generatedContent = aiData.choices?.[0]?.message?.content;

    if (!generatedContent) {
      console.error("No content in AI response");
      return new Response(
        JSON.stringify({ error: "AI returned no content" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log("AI response received, length:", generatedContent.length);

    // 3. Validate the response
    let jsonld;
    try {
      // Try to extract JSON from markdown code blocks if present
      let jsonContent = generatedContent.trim();
      if (jsonContent.startsWith("```")) {
        const match = jsonContent.match(/```(?:json)?\s*([\s\S]*?)```/);
        if (match) {
          jsonContent = match[1].trim();
        }
      }
      
      jsonld = JSON.parse(jsonContent);
    } catch (parseError) {
      console.error("Failed to parse AI response as JSON:", parseError);
      return new Response(
        JSON.stringify({
          error: "AI did not return valid JSON",
          details: generatedContent.substring(0, 500)
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Basic validation
    const validationErrors: string[] = [];

    if (!jsonld["@context"]) {
      validationErrors.push("Missing @context");
    }

    if (!jsonld["@graph"] || !Array.isArray(jsonld["@graph"])) {
      validationErrors.push("Missing or invalid @graph array");
    }

    // Check for Organization node
    // TODO: In future, replace this validation with a check that the Organization node
    // matches the master Organization schema from settings.organization_schema_json
    const orgNode = jsonld["@graph"]?.find((node: any) =>
      node["@id"] === "https://www.shepherdneame.co.uk/#organization" &&
      node.name === "Shepherd Neame Limited"
    );

    if (!orgNode) {
      validationErrors.push("Missing required Organization node with correct @id and name");
    }

    // For beer pages, ensure no Product/Offer schema
    if (page.page_type === "beer_brand" || page.page_type === "beer_collection") {
      const hasCommerce = jsonld["@graph"]?.some((node: any) => {
        const types = Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]];
        return types.some((t: string) =>
          ["Product", "Offer", "AggregateOffer", "ProductModel", "ItemList"].includes(t)
        );
      });

      if (hasCommerce) {
        validationErrors.push("Beer pages must not include Product or Offer schema");
      }
    }

    if (validationErrors.length > 0) {
      console.error("Validation errors:", validationErrors);
      return new Response(
        JSON.stringify({
          error: "Schema validation failed",
          validation_errors: validationErrors
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 4. Save schema version
    const jsonldString = JSON.stringify(jsonld, null, 2);

    // Calculate hash
    const encoder = new TextEncoder();
    const data = encoder.encode(jsonldString);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const schemaHash = hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");

    // Get the next version number
    const { data: existingVersions, error: versionsError } = await supabase
      .from("schema_versions")
      .select("version_number")
      .eq("page_id", page_id)
      .order("version_number", { ascending: false })
      .limit(1);

    const nextVersionNumber = existingVersions && existingVersions.length > 0
      ? existingVersions[0].version_number + 1
      : 1;

    // Insert schema version
    const { data: schemaVersion, error: schemaError } = await supabase
      .from("schema_versions")
      .insert({
        page_id: page_id,
        version_number: nextVersionNumber,
        jsonld: jsonldString,
        status: "draft",
        created_by_user_id: userId,
        rules_id: activeRule.id,
        google_rr_passed: false,
      })
      .select()
      .single();

    if (schemaError) {
      console.error("Error saving schema version:", schemaError);
      return new Response(
        JSON.stringify({ error: "Failed to save schema version" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Update page
    const { error: pageUpdateError } = await supabase
      .from("pages")
      .update({
        last_schema_generated_at: new Date().toISOString(),
        last_schema_hash: schemaHash,
        status: "ai_draft",
        last_modified_by_user_id: userId,
      })
      .eq("id", page_id);

    if (pageUpdateError) {
      console.error("Error updating page:", pageUpdateError);
    }

    // 6. Audit log
    await supabase.from("audit_log").insert({
      user_id: userId || "system",
      entity_type: "schema_version",
      entity_id: schemaVersion.id,
      action: "generate_schema",
      details: {
        page_id: page_id,
        page_path: page.path,
        version_number: nextVersionNumber,
        rule_id: activeRule.id,
        rule_name: activeRule.name,
      },
    });

    console.log("Schema generation completed successfully");

    return new Response(
      JSON.stringify({
        success: true,
        schema_version: schemaVersion,
        version_number: nextVersionNumber,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error in generate-schema function:", error);
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : "Unknown error",
      }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

